// Generated by gencpp from file robtrj/msgvarResponse.msg
// DO NOT EDIT!


#ifndef ROBTRJ_MESSAGE_MSGVARRESPONSE_H
#define ROBTRJ_MESSAGE_MSGVARRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robtrj
{
template <class ContainerAllocator>
struct msgvarResponse_
{
  typedef msgvarResponse_<ContainerAllocator> Type;

  msgvarResponse_()
    : x1()
    , y1()
    , theta1()  {
    }
  msgvarResponse_(const ContainerAllocator& _alloc)
    : x1(_alloc)
    , y1(_alloc)
    , theta1(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _x1_type;
  _x1_type x1;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _y1_type;
  _y1_type y1;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _theta1_type;
  _theta1_type theta1;





  typedef boost::shared_ptr< ::robtrj::msgvarResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robtrj::msgvarResponse_<ContainerAllocator> const> ConstPtr;

}; // struct msgvarResponse_

typedef ::robtrj::msgvarResponse_<std::allocator<void> > msgvarResponse;

typedef boost::shared_ptr< ::robtrj::msgvarResponse > msgvarResponsePtr;
typedef boost::shared_ptr< ::robtrj::msgvarResponse const> msgvarResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robtrj::msgvarResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robtrj::msgvarResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robtrj::msgvarResponse_<ContainerAllocator1> & lhs, const ::robtrj::msgvarResponse_<ContainerAllocator2> & rhs)
{
  return lhs.x1 == rhs.x1 &&
    lhs.y1 == rhs.y1 &&
    lhs.theta1 == rhs.theta1;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robtrj::msgvarResponse_<ContainerAllocator1> & lhs, const ::robtrj::msgvarResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robtrj

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robtrj::msgvarResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robtrj::msgvarResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robtrj::msgvarResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robtrj::msgvarResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robtrj::msgvarResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robtrj::msgvarResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robtrj::msgvarResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb585d5c5a493800085da0741bb6782c";
  }

  static const char* value(const ::robtrj::msgvarResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb585d5c5a493800ULL;
  static const uint64_t static_value2 = 0x085da0741bb6782cULL;
};

template<class ContainerAllocator>
struct DataType< ::robtrj::msgvarResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robtrj/msgvarResponse";
  }

  static const char* value(const ::robtrj::msgvarResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robtrj::msgvarResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] x1\n"
"float64[] y1\n"
"float64[] theta1\n"
"\n"
;
  }

  static const char* value(const ::robtrj::msgvarResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robtrj::msgvarResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x1);
      stream.next(m.y1);
      stream.next(m.theta1);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct msgvarResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robtrj::msgvarResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robtrj::msgvarResponse_<ContainerAllocator>& v)
  {
    s << indent << "x1[]" << std::endl;
    for (size_t i = 0; i < v.x1.size(); ++i)
    {
      s << indent << "  x1[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.x1[i]);
    }
    s << indent << "y1[]" << std::endl;
    for (size_t i = 0; i < v.y1.size(); ++i)
    {
      s << indent << "  y1[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.y1[i]);
    }
    s << indent << "theta1[]" << std::endl;
    for (size_t i = 0; i < v.theta1.size(); ++i)
    {
      s << indent << "  theta1[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.theta1[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBTRJ_MESSAGE_MSGVARRESPONSE_H
