// Generated by gencpp from file robtrj/msgvar.msg
// DO NOT EDIT!


#ifndef ROBTRJ_MESSAGE_MSGVAR_H
#define ROBTRJ_MESSAGE_MSGVAR_H

#include <ros/service_traits.h>


#include <robtrj/msgvarRequest.h>
#include <robtrj/msgvarResponse.h>


namespace robtrj
{

struct msgvar
{

typedef msgvarRequest Request;
typedef msgvarResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct msgvar
} // namespace robtrj


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robtrj::msgvar > {
  static const char* value()
  {
    return "950e2d113524791ab9fa7776cea26257";
  }

  static const char* value(const ::robtrj::msgvar&) { return value(); }
};

template<>
struct DataType< ::robtrj::msgvar > {
  static const char* value()
  {
    return "robtrj/msgvar";
  }

  static const char* value(const ::robtrj::msgvar&) { return value(); }
};


// service_traits::MD5Sum< ::robtrj::msgvarRequest> should match
// service_traits::MD5Sum< ::robtrj::msgvar >
template<>
struct MD5Sum< ::robtrj::msgvarRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robtrj::msgvar >::value();
  }
  static const char* value(const ::robtrj::msgvarRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robtrj::msgvarRequest> should match
// service_traits::DataType< ::robtrj::msgvar >
template<>
struct DataType< ::robtrj::msgvarRequest>
{
  static const char* value()
  {
    return DataType< ::robtrj::msgvar >::value();
  }
  static const char* value(const ::robtrj::msgvarRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robtrj::msgvarResponse> should match
// service_traits::MD5Sum< ::robtrj::msgvar >
template<>
struct MD5Sum< ::robtrj::msgvarResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robtrj::msgvar >::value();
  }
  static const char* value(const ::robtrj::msgvarResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robtrj::msgvarResponse> should match
// service_traits::DataType< ::robtrj::msgvar >
template<>
struct DataType< ::robtrj::msgvarResponse>
{
  static const char* value()
  {
    return DataType< ::robtrj::msgvar >::value();
  }
  static const char* value(const ::robtrj::msgvarResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBTRJ_MESSAGE_MSGVAR_H
