// Generated by gencpp from file robtrj/msgvarRequest.msg
// DO NOT EDIT!


#ifndef ROBTRJ_MESSAGE_MSGVARREQUEST_H
#define ROBTRJ_MESSAGE_MSGVARREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robtrj
{
template <class ContainerAllocator>
struct msgvarRequest_
{
  typedef msgvarRequest_<ContainerAllocator> Type;

  msgvarRequest_()
    : x(0.0)
    , y(0.0)
    , theta(0.0)
    , v(0.0)
    , w(0.0)  {
    }
  msgvarRequest_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , theta(0.0)
    , v(0.0)
    , w(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _theta_type;
  _theta_type theta;

   typedef double _v_type;
  _v_type v;

   typedef double _w_type;
  _w_type w;





  typedef boost::shared_ptr< ::robtrj::msgvarRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robtrj::msgvarRequest_<ContainerAllocator> const> ConstPtr;

}; // struct msgvarRequest_

typedef ::robtrj::msgvarRequest_<std::allocator<void> > msgvarRequest;

typedef boost::shared_ptr< ::robtrj::msgvarRequest > msgvarRequestPtr;
typedef boost::shared_ptr< ::robtrj::msgvarRequest const> msgvarRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robtrj::msgvarRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robtrj::msgvarRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robtrj::msgvarRequest_<ContainerAllocator1> & lhs, const ::robtrj::msgvarRequest_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.theta == rhs.theta &&
    lhs.v == rhs.v &&
    lhs.w == rhs.w;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robtrj::msgvarRequest_<ContainerAllocator1> & lhs, const ::robtrj::msgvarRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robtrj

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robtrj::msgvarRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robtrj::msgvarRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robtrj::msgvarRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robtrj::msgvarRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robtrj::msgvarRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robtrj::msgvarRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robtrj::msgvarRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f34e1ff6a445994ba1107842b60df510";
  }

  static const char* value(const ::robtrj::msgvarRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf34e1ff6a445994bULL;
  static const uint64_t static_value2 = 0xa1107842b60df510ULL;
};

template<class ContainerAllocator>
struct DataType< ::robtrj::msgvarRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robtrj/msgvarRequest";
  }

  static const char* value(const ::robtrj::msgvarRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robtrj::msgvarRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
"float64 theta\n"
"float64 v\n"
"float64 w\n"
"\n"
;
  }

  static const char* value(const ::robtrj::msgvarRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robtrj::msgvarRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.theta);
      stream.next(m.v);
      stream.next(m.w);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct msgvarRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robtrj::msgvarRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robtrj::msgvarRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "theta: ";
    Printer<double>::stream(s, indent + "  ", v.theta);
    s << indent << "v: ";
    Printer<double>::stream(s, indent + "  ", v.v);
    s << indent << "w: ";
    Printer<double>::stream(s, indent + "  ", v.w);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBTRJ_MESSAGE_MSGVARREQUEST_H
