// Generated by gencpp from file turtbot/angvelResponse.msg
// DO NOT EDIT!


#ifndef TURTBOT_MESSAGE_ANGVELRESPONSE_H
#define TURTBOT_MESSAGE_ANGVELRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtbot
{
template <class ContainerAllocator>
struct angvelResponse_
{
  typedef angvelResponse_<ContainerAllocator> Type;

  angvelResponse_()
    : vel(0.0)  {
    }
  angvelResponse_(const ContainerAllocator& _alloc)
    : vel(0.0)  {
  (void)_alloc;
    }



   typedef float _vel_type;
  _vel_type vel;





  typedef boost::shared_ptr< ::turtbot::angvelResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtbot::angvelResponse_<ContainerAllocator> const> ConstPtr;

}; // struct angvelResponse_

typedef ::turtbot::angvelResponse_<std::allocator<void> > angvelResponse;

typedef boost::shared_ptr< ::turtbot::angvelResponse > angvelResponsePtr;
typedef boost::shared_ptr< ::turtbot::angvelResponse const> angvelResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtbot::angvelResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtbot::angvelResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::turtbot::angvelResponse_<ContainerAllocator1> & lhs, const ::turtbot::angvelResponse_<ContainerAllocator2> & rhs)
{
  return lhs.vel == rhs.vel;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::turtbot::angvelResponse_<ContainerAllocator1> & lhs, const ::turtbot::angvelResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace turtbot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::turtbot::angvelResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtbot::angvelResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtbot::angvelResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtbot::angvelResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtbot::angvelResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtbot::angvelResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtbot::angvelResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "378ca590f55ecb8d30867c8ddf1db3c5";
  }

  static const char* value(const ::turtbot::angvelResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x378ca590f55ecb8dULL;
  static const uint64_t static_value2 = 0x30867c8ddf1db3c5ULL;
};

template<class ContainerAllocator>
struct DataType< ::turtbot::angvelResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtbot/angvelResponse";
  }

  static const char* value(const ::turtbot::angvelResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtbot::angvelResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 vel\n"
"\n"
;
  }

  static const char* value(const ::turtbot::angvelResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtbot::angvelResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct angvelResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtbot::angvelResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtbot::angvelResponse_<ContainerAllocator>& v)
  {
    s << indent << "vel: ";
    Printer<float>::stream(s, indent + "  ", v.vel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTBOT_MESSAGE_ANGVELRESPONSE_H
