// Generated by gencpp from file turtbot/angvelRequest.msg
// DO NOT EDIT!


#ifndef TURTBOT_MESSAGE_ANGVELREQUEST_H
#define TURTBOT_MESSAGE_ANGVELREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtbot
{
template <class ContainerAllocator>
struct angvelRequest_
{
  typedef angvelRequest_<ContainerAllocator> Type;

  angvelRequest_()
    : radius(0.0)  {
    }
  angvelRequest_(const ContainerAllocator& _alloc)
    : radius(0.0)  {
  (void)_alloc;
    }



   typedef float _radius_type;
  _radius_type radius;





  typedef boost::shared_ptr< ::turtbot::angvelRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtbot::angvelRequest_<ContainerAllocator> const> ConstPtr;

}; // struct angvelRequest_

typedef ::turtbot::angvelRequest_<std::allocator<void> > angvelRequest;

typedef boost::shared_ptr< ::turtbot::angvelRequest > angvelRequestPtr;
typedef boost::shared_ptr< ::turtbot::angvelRequest const> angvelRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtbot::angvelRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtbot::angvelRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::turtbot::angvelRequest_<ContainerAllocator1> & lhs, const ::turtbot::angvelRequest_<ContainerAllocator2> & rhs)
{
  return lhs.radius == rhs.radius;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::turtbot::angvelRequest_<ContainerAllocator1> & lhs, const ::turtbot::angvelRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace turtbot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::turtbot::angvelRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtbot::angvelRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtbot::angvelRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtbot::angvelRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtbot::angvelRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtbot::angvelRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtbot::angvelRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0b690044065f2210effb664cc7a28125";
  }

  static const char* value(const ::turtbot::angvelRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0b690044065f2210ULL;
  static const uint64_t static_value2 = 0xeffb664cc7a28125ULL;
};

template<class ContainerAllocator>
struct DataType< ::turtbot::angvelRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtbot/angvelRequest";
  }

  static const char* value(const ::turtbot::angvelRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtbot::angvelRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 radius\n"
;
  }

  static const char* value(const ::turtbot::angvelRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtbot::angvelRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.radius);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct angvelRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtbot::angvelRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtbot::angvelRequest_<ContainerAllocator>& v)
  {
    s << indent << "radius: ";
    Printer<float>::stream(s, indent + "  ", v.radius);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTBOT_MESSAGE_ANGVELREQUEST_H
